AWSTemplateFormatVersion: '2010-09-09'
Description: Jenkins Server

Resources:
  JenkinsServerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'ec2.amazonaws.com'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
      RoleName: 'JenkinsServerRole'

  JenkinsServerInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref JenkinsServerRole

  JenkinsServer:
    Type: 'AWS::EC2::Instance'
    Properties: 
      InstanceType: t2.micro
      KeyName: my-key
      ImageId: ami-0abcdef1234567890
      SecurityGroups: 
        - my-security-group
      IamInstanceProfile: !Ref JenkinsServerInstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -ex
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          # Remove the expired Jenkins key
          sudo apt-key del 5BA31D57EF5975CA
          # Add Jenkins key and repository
          curl -fsSL https://pkg.jenkins.io/debian/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
          echo 'deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] http://pkg.jenkins.io/debian-stable binary/' | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk jenkins
          sudo systemctl start jenkins
          sudo systemctl enable jenkins
         
